language: android
jdk:
    - oraclejdk8
env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

android:
  components:
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

script:
  - ./gradlew check